#配置vsftpd
ftpclient:
  host: 192.168.109.128
  port: 21
  username: ftpuser
  password: llf100499
  basePath: /home/ftpuser/
  filePath: /

search:
  url: http://localhost:8088/solr/add
passport:
  url: http://localhost:8082/user/token/
cart:
  key: cart: